# Generated by Django 4.2.1 on 2023-06-1 21:21

from django.db import migrations

def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')  # Importa o modelo Group do Django
    groups = ['Bolsista', 'Patrocinador', 'Colaborador', 'Admin']  # Lista de grupos a serem adicionados

    for group_name in groups:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]