# Generated by Django 4.2.1 on 2023-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('regular', 'regular'), ('bolsista', 'bolsista'), ('colaborador', 'colaborador'), ('administrador', 'administrador'), ('sponsor', 'sponsor')], default='regular', max_length=100),
        ),
    ]
