# Generated by Django 4.2.1 on 2023-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='profile',
            name='ano_formatura',
            field=models.CharField(max_length=4, null=True, verbose_name='Ano de Formatura'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ano_ingresso',
            field=models.CharField(max_length=4, null=True, verbose_name='Ano de Ingresso'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_atual',
            field=models.CharField(blank=True, choices=[('china', 'china'), ('hong kong', 'hong kong'), ('India', 'India')], max_length=100, null=True, verbose_name='Cidade Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_fora_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Fora Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_nascimento',
            field=models.CharField(blank=True, choices=[('china', 'china'), ('hong kong', 'hong kong'), ('India', 'India')], max_length=100, null=True, verbose_name='Cidade de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cor_ou_raca',
            field=models.CharField(choices=[('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indígena', 'Indígena'), ('Parda', 'Parda'), ('Preta', 'Preta'), ('Prefiro não informar', 'Prefiro não informar'), ('Outra', 'Outra')], max_length=20, null=True, verbose_name='Cor ou Raça'),
        ),
        migrations.AddField(
            model_name='profile',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_atual',
            field=models.CharField(blank=True, choices=[('china', 'china'), ('hong kong', 'hong kong'), ('India', 'India')], max_length=100, null=True, verbose_name='Estado Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_nascimento',
            field=models.CharField(blank=True, choices=[('china', 'china'), ('hong kong', 'hong kong'), ('India', 'India')], max_length=100, null=True, verbose_name='Estado de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculdade',
            field=models.CharField(blank=True, choices=[('Insper', 'Insper'), ('Inteli', 'Inteli'), ('Facul3', 'Facul3')], max_length=100, null=True, verbose_name='Faculdade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='sprint/static/profile_img', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Prefiro não informar', 'Prefiro não informar'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nome_exibicao',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome de exibição'),
        ),
        migrations.AddField(
            model_name='profile',
            name='outra_cor_ou_raca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='outro_genero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outro'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pais_atual',
            field=models.CharField(blank=True, choices=[('china', 'china'), ('hong kong', 'hong kong'), ('India', 'India')], max_length=100, null=True, verbose_name='País Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='renda_familiar',
            field=models.CharField(blank=True, choices=[('0-1 SM', '0-1 SM'), ('1-2 SM', '1-2 SM'), ('2-3 SM', '2-3 SM'), ('3-5 SM', '3-5 SM'), ('5-8 SM', '5-8 SM'), ('8+ SM', '8+ SM')], max_length=100, null=True, verbose_name='Renda Familiar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rg',
            field=models.CharField(max_length=12, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sobrenome',
            field=models.CharField(max_length=150, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=19, null=True, verbose_name='Numero de Telefone'),
        ),
    ]
