# Generated by Django 4.2.1 on 2023-05-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_cor_ou_raca_alter_profile_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ano_formatura',
            field=models.DateField(null=True, verbose_name='Ano de Formatura'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ano_ingresso',
            field=models.DateField(null=True, verbose_name='Ano de Ingresso'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_fora_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Fora Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade_nascimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_nascimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculdade',
            field=models.CharField(blank=True, choices=[('Insper', 'Insper'), ('Inteli', 'Inteli'), ('Facul3', 'Facul3')], max_length=100, null=True, verbose_name='Faculdade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pais_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País Atual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='renda_familiar',
            field=models.CharField(blank=True, choices=[('0-1 SM', '0-1 SM'), ('1-2 SM', '1-2 SM'), ('2-3 SM', '2-3 SM'), ('3-5 SM', '3-5 SM'), ('5-8 SM', '5-8 SM'), ('8+ SM', '8+ SM')], max_length=100, null=True, verbose_name='Renda Familiar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('Bolsista', 'Bolsista'), ('Alumni', 'Alumni')], max_length=100, null=True, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=18, null=True, verbose_name='Numero de Telefone'),
        ),
    ]
