# Generated by Django 4.2.1 on 2023-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_ano_formatura_profile_ano_ingresso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sobrenome',
            field=models.CharField(max_length=150, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cidade_atual',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('china', 'china'), ('hong kong', 'hong kong')], max_length=100, null=True, verbose_name='Cidade Atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cidade_nascimento',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('china', 'china'), ('hong kong', 'hong kong')], max_length=100, null=True, verbose_name='Cidade de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado_atual',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('china', 'china'), ('hong kong', 'hong kong')], max_length=100, null=True, verbose_name='Estado Atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado_nascimento',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('china', 'china'), ('hong kong', 'hong kong')], max_length=100, null=True, verbose_name='Estado de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pais_atual',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('china', 'china'), ('hong kong', 'hong kong')], max_length=100, null=True, verbose_name='País Atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=19, null=True, verbose_name='Numero de Telefone'),
        ),
    ]
