# Generated by Django 4.2.1 on 2023-05-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_cidade_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='sprint/static/img', verbose_name='Foto de Perfil'),
        ),
    ]
