# Generated by Django 4.2.1 on 2023-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
