# Generated by Django 4.2.1 on 2023-05-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_tipo_usuario'),
        ('users', '0009_remove_profile_foto_de_perfil_profile_foto_perfil'),
    ]

    operations = [
    ]
