# Generated by Django 4.2.1 on 2023-06-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20230531_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cidade_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cidade_nascimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado_atual',
            field=models.CharField(blank=True, choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=100, null=True, verbose_name='Estado Atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado_nascimento',
            field=models.CharField(blank=True, choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=100, null=True, verbose_name='Estado de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pais_atual',
            field=models.CharField(blank=True, choices=[('Alemanha', 'Alemanha'), ('Brasil', 'Brasil'), ('China', 'China'), ('Estados Unidos', 'Estados Unidos'), ('Holanda', 'Holanda'), ('India', 'India'), ('Reino Unido', 'Reino Unido'), ('Russia', 'Russia'), ('Senegal', 'Senegal'), ('Suiça', 'Suiça')], max_length=100, null=True, verbose_name='País Atual'),
        ),
    ]
