# Generated by Django 4.2.1 on 2023-06-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_cidade_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('Bolsista', 'Bolsista'), ('Alumni', 'Alumni'), ('Sponsor', 'Sponsor'), ('Colaborador', 'Colaborador'), ('Admin', 'Admin')], max_length=100, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
