# Generated by Django 4.2.1 on 2023-06-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
