# Generated by Django 4.2.1 on 2023-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proprietario', models.CharField(blank=True, max_length=100, null=True, verbose_name='id_proprietario')),
                ('media', models.CharField(blank=True, max_length=100, null=True, verbose_name='media escolar')),
                ('campo_extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='campo extra')),
                ('semestre_atual', models.CharField(blank=True, max_length=100, null=True, verbose_name='semestre atual')),
                ('pdf', models.FileField(upload_to='sprint/static/pdfs')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
