# Generated by Django 4.2.1 on 2023-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_historicoescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proprietario', models.CharField(blank=True, max_length=100, null=True, verbose_name='id_proprietario')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='empresa')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='cargo')),
                ('setor_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='setor_empresa')),
                ('salario', models.CharField(blank=True, max_length=100, null=True, verbose_name='salario')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
