# Generated by Django 4.2.1 on 2023-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_historicoprofissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoescolar',
            name='id_proprietario',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_proprietario'),
        ),
        migrations.AlterField(
            model_name='historicoprofissional',
            name='id_proprietario',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_proprietario'),
        ),
    ]
