# Generated by Django 4.2.1 on 2023-06-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_historicoescolar_id_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoprofissional',
            name='data_inicio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='data_inicio'),
        ),
    ]
