# Generated by Django 4.2.1 on 2023-06-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_historicoprofissional_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicoprofissional',
            old_name='data_inicio',
            new_name='data_ingresso',
        ),
    ]
