# Generated by Django 4.2.1 on 2023-06-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_keys'),
        ('users', '0018_alter_historicoprofissional_data_ingresso'),
    ]

    operations = [
    ]
