# Generated by Django 4.2.1 on 2023-06-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_ultima_atualizacao'),
        ('users', '0019_merge_20230607_0109'),
    ]

    operations = [
    ]
