# Generated by Django 4.2.1 on 2023-06-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20230607_0140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoEscolar',
            new_name='HistoricoAcademico',
        ),
    ]
