# Generated by Django 4.2.1 on 2023-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20230607_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ano_formatura',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de Formatura'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ano_ingresso',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de Ingresso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cor_ou_raca',
            field=models.CharField(blank=True, choices=[('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indígena', 'Indígena'), ('Parda', 'Parda'), ('Preta', 'Preta'), ('Prefiro não informar', 'Prefiro não informar'), ('Outra', 'Outra')], max_length=20, null=True, verbose_name='Cor ou Raça'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Prefiro não informar', 'Prefiro não informar'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome de exibição'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rg',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Numero de Telefone'),
        ),
    ]
