# Generated by Django 4.2.1 on 2023-06-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_ano_formatura_and_more'),
        ('users', '0021_rename_historicoescolar_historicoacademico'),
    ]

    operations = [
    ]
