# Generated by Django 4.2.1 on 2023-06-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20230607_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Número de Telefone'),
        ),
    ]
