# Generated by Django 4.2.1 on 2023-06-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cor_ou_raca',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indígena', 'Indígena'), ('Parda', 'Parda'), ('Preta', 'Preta'), ('Prefiro não informar', 'Prefiro não informar'), ('Outra', 'Outra')], max_length=20, null=True, verbose_name='Cor ou Raça'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado_atual',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=100, null=True, verbose_name='Estado Atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado_nascimento',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=100, null=True, verbose_name='Estado de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculdade',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('Insper', 'Insper'), ('Inteli', 'Inteli'), ('Facul3', 'Facul3')], max_length=100, null=True, verbose_name='Faculdade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Prefiro não informar', 'Prefiro não informar'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pais_atual',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('Alemanha', 'Alemanha'), ('Brasil', 'Brasil'), ('China', 'China'), ('Estados Unidos', 'Estados Unidos'), ('Holanda', 'Holanda'), ('India', 'India'), ('Reino Unido', 'Reino Unido'), ('Russia', 'Russia'), ('Senegal', 'Senegal'), ('Suiça', 'Suiça')], max_length=100, null=True, verbose_name='País Atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='renda_familiar',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('0-1 SM', '0-1 SM'), ('1-2 SM', '1-2 SM'), ('2-3 SM', '2-3 SM'), ('3-5 SM', '3-5 SM'), ('5-8 SM', '5-8 SM'), ('8+ SM', '8+ SM')], max_length=100, null=True, verbose_name='Renda Familiar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('-----', '-----'), ('Bolsista', 'Bolsista'), ('Alumni', 'Alumni'), ('Sponsor', 'Sponsor'), ('Colaborador', 'Colaborador'), ('Admin', 'Admin')], max_length=100, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
